SC-4632: Load & Stress Test Tool
spryker-sdk/load-testing pull request #1
Opened 2020-12-15 12:29 UTC by sprymiker

2020-12-15 12:34 UTC, alexanderM91 commented on .travis.yml
> +    - 7.2
Please update to 7.3

2020-12-15 12:35 UTC, alexanderM91 commented on composer.json
> +    "php": ">=7.2",
The same

2020-12-15 12:39 UTC, alexanderM91 approved these changes

2020-12-15 13:28 UTC, dereuromark commented
Please dont use the word module with a library.
Also in composer, changelogs and README etc.

2020-12-15 13:29 UTC, dereuromark commented
Are you sure the license in the master branch is correct for SprykerSDK?

2020-12-15 13:32 UTC, dereuromark requested changes
`/src/`
as per internal (quite new) rule must not contain anything but psr4 autoloadable files for any PHP repo of ours.
All others (e.g. templates) must be removed from here and instead be in resources/ or some other top level folder or alike.

2020-12-16 14:36 UTC, zyuzka commented
@dereuromark Hello and thank you for your advice.

1. Module word was updated on a tool 
2. License we took from https://github.com/spryker-sdk/benchmark
3. Folder structure was updated

2021-01-22 11:25 UTC, merged